// cyberia master map — catalog + construction site traced from master-plan screenshot
// scale: plot area 0.096 ha (google maps) => 13.45 px/m; north up; cell = 4 m
// generated by tools/trace_site0.py — edit the trace, then regenerate

const CATALOG = [
  { id: 'cube',     name: 'CUBE-4',   sub: '4×4×4 multipurpose cell', tag: 'CELL',    status: 'P0', glyph: 'C' },
  { id: 'tube',     name: 'TUBE',     sub: 'living connector S · M',  tag: 'LINK',    status: 'P0', glyph: 'T' },
  { id: 'prysm',    name: 'PRYSM',    sub: 'half-rhomb triangle',     tag: 'MODULE',  status: 'P1', glyph: 'P' },
  { id: 'pyramid',  name: 'PYRAMID',  sub: 'reception · market · grill', tag: 'HUB',  status: 'P1', glyph: 'Y' },
  { id: 'sphere',   name: 'SPHERE',   sub: 'water store + orangery',  tag: 'CORE',    status: 'P1', glyph: 'S' },
];

const ACTIONS = ['SURVEY', 'CLEAR', 'PLANT', 'HAUL', 'WATCH', 'BUILD'];

const TUBE_CONTENT = [
  'closed pond', 'glass path top', 'vines', 'glass + wood', 'algae bioreactor',
  'herbs', 'berries', 'veggies', 'flowers', 'bees', 'birds', 'rabbits',
  'chicks', 'rainbow python', 'flying fox',
];

const PYRAMID_FN = [
  'reception', 'shop', 'grill', 'cafe', 'organics', 'tools', 'tech',
  'accums', 'chargers', 'delivery', 'post', 'play zone', 'outfit',
  'fabrics', 'leather', 'jewels', 'robots', 'sweets',
];

const PRYSM_MAT = ['wood', 'glass', 'metal'];

// map viewport: 973 × 878 units = 60.8 × 54.9 m
const MAP_W = 973, MAP_H = 878, CELL = 64; // cell = 4 m
const METER = 16.0; // svg units per meter
const PLOT_AREA_M2 = 960; // 0.096 ha per google maps

const FLATS = [
  {
    id: 'site-0', name: 'SITE 0', color: '#52e05a',
    fill: 'rgba(46, 160, 67, 0.30)',
    note: 'construction site · 0.096 ha · google maps',
    pts: [[359.3, 135.6], [491.3, 151.1], [622.2, 163.0], [637.7, 222.5], [661.4, 268.9], [718.5, 302.2], [782.8, 355.7], [848.2, 419.9], [926.7, 480.6], [878.0, 559.1], [818.5, 637.7], [726.9, 780.4], [464.0, 594.8], [196.3, 404.5], [247.4, 346.2], [297.4, 287.9], [329.5, 210.6]],
  },
];

// neighbour parcel across the road (from the same screenshot)
const CONTEXT = [{"name": "neighbour parcel", "kind": "certificates", "pts": [[973.1, 518.7], [904.1, 537.7], [832.8, 628.1], [770.9, 720.9], [713.8, 878.0], [973.1, 878.0]]}];

// road + trails traced from the screenshot
const LINES = [{"name": "road", "pts": [[973.1, 437.8], [935.1, 480.6], [888.7, 549.6], [832.8, 628.1], [768.5, 725.7], [722.1, 794.7], [687.6, 856.5], [666.2, 878.0]]}, {"name": "trail", "pts": [[114.2, 437.8], [166.6, 356.9], [226.0, 267.7], [285.5, 178.4], [356.9, 95.2], [428.3, 47.6]]}, {"name": "trail", "pts": [[356.9, 95.2], [511.5, 83.3], [666.2, 71.4], [832.8, 107.1]]}, {"name": "trail", "pts": [[666.2, 71.4], [785.2, 142.8], [904.1, 261.7], [951.7, 356.9]]}, {"name": "trail", "pts": [[114.2, 437.8], [214.1, 499.7], [356.9, 571.0], [499.7, 666.2], [618.6, 773.3], [666.2, 878.0]]}];

const PLACES = [];

const MY_MAPS_ID = '1txZioQKBBvOdmox1Had5aI-Zz4kUEJI';

function defaultConfig(id) {
  switch (id) {
    case 'cube':     return { mode: 'unit', pax: 1, purpose: '', walls: [] };
    case 'tube':     return { size: 'S', len: 8, content: ['closed pond', 'glass path top'] };
    case 'prysm':    return { h: 2, mat: ['wood', 'glass'], modular: true };
    case 'pyramid':  return { fns: ['reception', 'shop', 'cafe'] };
    case 'sphere':   return { water: true, orangery: true };
    default:         return {};
  }
}
