// cyberia master map — catalog + construction site traced from master-plan screenshot
// scale: approx, road width ≈ 4 m => 3.5 px/m; north up; cell = 4 m
// generated by tools/trace_site0.py — edit the trace or PX_PER_M, then regenerate

const CATALOG = [
  { id: 'cube',     name: 'CUBE-4',   sub: '4×4×4 multipurpose cell', tag: 'CELL',    status: 'P0', glyph: 'C' },
  { id: 'tube',     name: 'TUBE',     sub: 'living connector S · M',  tag: 'LINK',    status: 'P0', glyph: 'T' },
  { id: 'prysm',    name: 'PRYSM',    sub: 'half-rhomb triangle',     tag: 'MODULE',  status: 'P1', glyph: 'P' },
  { id: 'pyramid',  name: 'PYRAMID',  sub: 'reception · market · grill', tag: 'HUB',  status: 'P1', glyph: 'Y' },
  { id: 'sphere',   name: 'SPHERE',   sub: 'water store + orangery',  tag: 'CORE',    status: 'P1', glyph: 'S' },
];

const ACTIONS = ['SURVEY', 'CLEAR', 'PLANT', 'HAUL', 'WATCH', 'BUILD'];

const TUBE_CONTENT = [
  'closed pond', 'glass path top', 'vines', 'glass + wood', 'algae bioreactor',
  'herbs', 'berries', 'veggies', 'flowers', 'bees', 'birds', 'rabbits',
  'chicks', 'rainbow python', 'flying fox',
];

const PYRAMID_FN = [
  'reception', 'shop', 'grill', 'cafe', 'organics', 'tools', 'tech',
  'accums', 'chargers', 'delivery', 'post', 'play zone', 'outfit',
  'fabrics', 'leather', 'jewels', 'robots', 'sweets',
];

const PRYSM_MAT = ['wood', 'glass', 'metal'];

// map viewport: 1169 × 1054 units = 234 × 211 m (scale approx)
const MAP_W = 1169, MAP_H = 1054, CELL = 20; // cell = 4 m
const METER = 5.0; // svg units per meter

const FLATS = [
  {
    id: 'site-0', name: 'SITE 0', color: '#52e05a',
    fill: 'rgba(46, 160, 67, 0.30)',
    note: 'construction site · 17 points · ≈1.4 ha (scale approx)',
    pts: [[431.4, 162.9], [590.0, 181.4], [747.1, 195.7], [765.7, 267.1], [794.3, 322.9], [862.9, 362.9], [940.0, 427.1], [1018.6, 504.3], [1112.9, 577.1], [1054.3, 671.4], [982.9, 765.7], [872.9, 937.1], [557.1, 714.3], [235.7, 485.7], [297.1, 415.7], [357.1, 345.7], [395.7, 252.9]],
  },
];

// neighbour parcel across the road (from the same screenshot)
const CONTEXT = [{"name": "neighbour parcel", "kind": "certificates", "pts": [[1168.6, 622.9], [1085.7, 645.7], [1000.0, 754.3], [925.7, 865.7], [857.1, 1054.3], [1168.6, 1054.3]]}];

// road + trails traced from the screenshot
const LINES = [{"name": "road", "pts": [[1168.6, 525.7], [1122.9, 577.1], [1067.1, 660.0], [1000.0, 754.3], [922.9, 871.4], [867.1, 954.3], [825.7, 1028.6], [800.0, 1054.3]]}, {"name": "trail", "pts": [[137.1, 525.7], [200.0, 428.6], [271.4, 321.4], [342.9, 214.3], [428.6, 114.3], [514.3, 57.1]]}, {"name": "trail", "pts": [[428.6, 114.3], [614.3, 100.0], [800.0, 85.7], [1000.0, 128.6]]}, {"name": "trail", "pts": [[800.0, 85.7], [942.9, 171.4], [1085.7, 314.3], [1142.9, 428.6]]}, {"name": "trail", "pts": [[137.1, 525.7], [257.1, 600.0], [428.6, 685.7], [600.0, 800.0], [742.9, 928.6], [800.0, 1054.3]]}];

const PLACES = [];

const MY_MAPS_ID = '1txZioQKBBvOdmox1Had5aI-Zz4kUEJI';

function defaultConfig(id) {
  switch (id) {
    case 'cube':     return { mode: 'unit', pax: 1, purpose: '', walls: [] };
    case 'tube':     return { size: 'S', len: 8, content: ['closed pond', 'glass path top'] };
    case 'prysm':    return { h: 2, mat: ['wood', 'glass'], modular: true };
    case 'pyramid':  return { fns: ['reception', 'shop', 'cafe'] };
    case 'sphere':   return { water: true, orangery: true };
    default:         return {};
  }
}
