# regenerate js/data.js from the cyber valley google-my-maps kml
# usage: curl -sL "https://www.google.com/maps/d/kml?mid=$MID&forcekml=1" -o cv.kml
#        python3 tools/gen_data.py cv.kml
import json, math, sys
import xml.etree.ElementTree as ET

NSK = '{http://www.opengis.net/kml/2.2}'
TARGET = ('certificates', 'rockets estate 1')
MID = '1txZioQKBBvOdmox1Had5aI-Zz4kUEJI'
SCALE, MARGIN = 5.0, 24.0  # svg units per meter, meters of margin

kml_path = sys.argv[1] if len(sys.argv) > 1 else 'cv.kml'
root = ET.parse(kml_path).getroot()

polys, points, lines_raw = [], [], []

def walk(el, path):
    for f in el.findall(NSK + 'Folder'):
        n = f.find(NSK + 'name')
        walk(f, path + [(n.text or '?').strip() if n is not None else '?'])
    for pm in el.findall(NSK + 'Placemark'):
        n = pm.find(NSK + 'name')
        name = (n.text or '').strip() if n is not None else ''
        folder = '/'.join(path)
        for tag, sink in (('Polygon', polys), ('LineString', lines_raw), ('Point', points)):
            for g in pm.iter(NSK + tag):
                co = g.find('.//' + NSK + 'coordinates')
                if co is None or not co.text:
                    continue
                pts = [tuple(map(float, t.split(',')[:2])) for t in co.text.split()]
                sink.append({'folder': folder, 'name': name, 'pts': pts})

walk(root.find(NSK + 'Document'), [])

tgt = next(p for p in polys if (p['folder'], p['name']) == TARGET)
lat0 = sum(q[1] for q in tgt['pts']) / len(tgt['pts'])
MX, MY = 111320 * math.cos(math.radians(lat0)), 110574

def to_m(lng, lat):
    return lng * MX, -lat * MY  # y grows south => north up

txs = [to_m(*q)[0] for q in tgt['pts']]
tys = [to_m(*q)[1] for q in tgt['pts']]
x0, y0 = min(txs) - MARGIN, min(tys) - MARGIN
x1, y1 = max(txs) + MARGIN, max(tys) + MARGIN
W, H = (x1 - x0) * SCALE, (y1 - y0) * SCALE

def px(lng, lat):
    mx, my = to_m(lng, lat)
    return round((mx - x0) * SCALE, 1), round((my - y0) * SCALE, 1)

def poly_px(pts):
    out = [list(px(*q)) for q in pts]
    return out[:-1] if out[0] == out[-1] else out

def shoelace_ha(pts):
    m = [to_m(*q) for q in pts]
    s = sum(m[i][0] * m[(i + 1) % len(m)][1] - m[(i + 1) % len(m)][0] * m[i][1]
            for i in range(len(m)))
    return abs(s) / 2 / 10000

def intersects(pts):
    m = [to_m(*q) for q in pts]
    xs = [q[0] for q in m]; ys = [q[1] for q in m]
    return not (max(xs) < x0 or min(xs) > x1 or max(ys) < y0 or min(ys) > y1)

def inside(x, y, pts):
    ins = False
    for i in range(len(pts)):
        xa, ya = pts[i]; xb, yb = pts[i - 1]
        if (ya > y) != (yb > y) and x < (xb - xa) * (y - ya) / (yb - ya) + xa:
            ins = not ins
    return ins

plot_pts = poly_px(tgt['pts'])
ha = shoelace_ha(tgt['pts'])

context = [{'name': p['name'], 'kind': p['folder'], 'pts': poly_px(p['pts'])}
           for p in polys
           if (p['folder'], p['name']) != TARGET
           and p['folder'] in ('districts', 'certificates', 'plots', 'friend sales')
           and intersects(p['pts'])]

lines = [{'name': l['name'], 'pts': [list(px(*q)) for q in l['pts']]}
         for l in lines_raw if intersects(l['pts'])]

places = []
for p in polys:
    if p['folder'] != 'places' or p['name'].lower().startswith('polygon'):
        continue
    m = [to_m(*q) for q in p['pts']]
    cx = sum(q[0] for q in m) / len(m); cy = sum(q[1] for q in m) / len(m)
    X, Y = round((cx - x0) * SCALE, 1), round((cy - y0) * SCALE, 1)
    if 0 <= X <= W and 0 <= Y <= H:
        places.append({'name': p['name'], 'x': X, 'y': Y, 'in': inside(X, Y, plot_pts)})
for q in points:
    if q['name'] in ('sign', 'bamboo', ''):
        continue
    X, Y = px(*q['pts'][0])
    if 0 <= X <= W and 0 <= Y <= H:
        places.append({'name': q['name'], 'x': X, 'y': Y, 'in': inside(X, Y, plot_pts)})
seen = set()
places = [p for p in places if not (p['name'] in seen or seen.add(p['name']))]
js_places = [p for p in places if p['in']][:14] or places[:8]

js = lambda v: json.dumps(v, ensure_ascii=False)

data = f"""// cyberia master map — catalog + real geometry from cyber valley my-maps kml
// source: google my maps {MID} · plot: rockets estate 1 (certificates layer)
// coordinates: meters, north up, {SCALE} svg units = 1 m · cell = 4 m
// generated by tools/gen_data.py — edit the generator, then regenerate

const CATALOG = [
  {{ id: 'cube',     name: 'CUBE-4',   sub: '4×4×4 multipurpose cell', tag: 'CELL',    status: 'P0', glyph: 'C' }},
  {{ id: 'tube',     name: 'TUBE',     sub: 'living connector S · M',  tag: 'LINK',    status: 'P0', glyph: 'T' }},
  {{ id: 'prysm',    name: 'PRYSM',    sub: 'half-rhomb triangle',     tag: 'MODULE',  status: 'P1', glyph: 'P' }},
  {{ id: 'pyramid',  name: 'PYRAMID',  sub: 'reception · market · grill', tag: 'HUB',  status: 'P1', glyph: 'Y' }},
  {{ id: 'sphere',   name: 'SPHERE',   sub: 'water store + orangery',  tag: 'CORE',    status: 'P1', glyph: 'S' }},
];

const ACTIONS = ['SURVEY', 'CLEAR', 'PLANT', 'HAUL', 'WATCH', 'BUILD'];

const TUBE_CONTENT = [
  'closed pond', 'glass path top', 'vines', 'glass + wood', 'algae bioreactor',
  'herbs', 'berries', 'veggies', 'flowers', 'bees', 'birds', 'rabbits',
  'chicks', 'rainbow python', 'flying fox',
];

const PYRAMID_FN = [
  'reception', 'shop', 'grill', 'cafe', 'organics', 'tools', 'tech',
  'accums', 'chargers', 'delivery', 'post', 'play zone', 'outfit',
  'fabrics', 'leather', 'jewels', 'robots', 'sweets',
];

const PRYSM_MAT = ['wood', 'glass', 'metal'];

// map viewport: {W:.0f} × {H:.0f} units = {(x1-x0):.0f} × {(y1-y0):.0f} m
const MAP_W = {W:.0f}, MAP_H = {H:.0f}, CELL = {4 * SCALE:.0f}; // cell = 4 m
const METER = {SCALE}; // svg units per meter

const FLATS = [
  {{
    id: 'rockets-estate-1', name: 'ROCKETS ESTATE 1', color: '#52e05a',
    fill: 'rgba(46, 160, 67, 0.30)',
    note: 'certificate · {len(plot_pts)} vertices · {ha:.2f} ha',
    pts: {js(plot_pts)},
  }},
];

// neighbour certificates / districts / plots (dim outlines)
const CONTEXT = {js(context)};

// paths and roads (kml linestrings)
const LINES = {js(lines)};

const PLACES = {js(js_places)};

const MY_MAPS_ID = '{MID}';

function defaultConfig(id) {{
  switch (id) {{
    case 'cube':     return {{ mode: 'unit', pax: 1, purpose: '', walls: [] }};
    case 'tube':     return {{ size: 'S', len: 8, content: ['closed pond', 'glass path top'] }};
    case 'prysm':    return {{ h: 2, mat: ['wood', 'glass'], modular: true }};
    case 'pyramid':  return {{ fns: ['reception', 'shop', 'cafe'] }};
    case 'sphere':   return {{ water: true, orangery: true }};
    default:         return {{}};
  }}
}}
"""
open('js/data.js', 'w').write(data)
print(f"plot {len(plot_pts)} v · {ha:.2f} ha · view {(x1-x0):.0f}×{(y1-y0):.0f} m · "
      f"context {len(context)} · lines {len(lines)} · places {len(js_places)}")
