# regenerate js/data.js from the construction-site screenshot trace
# source: master-plan my-maps screenshot (818×738 px frame, north up).
# the white-border polygon is traced dot-by-dot; my-maps midpoint handles
# lie exactly on the edge, so including them keeps the outline exact.
# scale: anchored to the official plot area from google maps: 0.096 ha.
import json, math

AREA_HA = 0.096          # plot area per google maps
SCALE = 16.0             # svg units per meter (matches app METER)
FRAME = (818, 738)       # px

SITE_PX = [
    (302, 114), (413, 127), (523, 137), (536, 187), (556, 226),
    (604, 254), (658, 299), (713, 353), (779, 404), (738, 470),
    (688, 536), (611, 656), (390, 500), (165, 340), (208, 291),
    (250, 242), (277, 177),
]

ROAD_PX = [(818, 368), (786, 404), (747, 462), (700, 528),
           (646, 610), (607, 668), (578, 720), (560, 738)]

NEIGHBOUR_PX = [(818, 436), (760, 452), (700, 528), (648, 606),
                (600, 738), (818, 738)]

TRAILS_PX = [
    [(96, 368), (140, 300), (190, 225), (240, 150), (300, 80), (360, 40)],
    [(300, 80), (430, 70), (560, 60), (700, 90)],
    [(560, 60), (660, 120), (760, 220), (800, 300)],
    [(96, 368), (180, 420), (300, 480), (420, 560), (520, 650), (560, 738)],
]

area_px = abs(sum(SITE_PX[i][0] * SITE_PX[(i + 1) % len(SITE_PX)][1]
                  - SITE_PX[(i + 1) % len(SITE_PX)][0] * SITE_PX[i][1]
                  for i in range(len(SITE_PX)))) / 2
PX_PER_M = math.sqrt(area_px / (AREA_HA * 10000))
PX2U = SCALE / PX_PER_M

u = lambda pts: [[round(x * PX2U, 1), round(y * PX2U, 1)] for x, y in pts]

site = u(SITE_PX)
W, H = round(FRAME[0] * PX2U), round(FRAME[1] * PX2U)
area_m2 = AREA_HA * 10000

js = lambda v: json.dumps(v, ensure_ascii=False)

data = f"""// cyberia master map — catalog + construction site traced from master-plan screenshot
// scale: plot area 0.096 ha (google maps) => {PX_PER_M:.2f} px/m; north up; cell = 4 m
// generated by tools/trace_site0.py — edit the trace, then regenerate

const CATALOG = [
  {{ id: 'cube',     name: 'CUBE-4',   sub: '4×4×4 m cell · 1 cell',        tag: 'CELL',   status: 'P0', glyph: 'C' }},
  {{ id: 'tube',     name: 'TUBE',     sub: '2/4 m × 4–16 m · 1–4 cells',   tag: 'LINK',   status: 'P0', glyph: 'T' }},
  {{ id: 'prysm',    name: 'PRYSM',    sub: 'base 4 m · h 2/4 · 1–2 cells', tag: 'MODULE', status: 'P1', glyph: 'P' }},
  {{ id: 'pyramid',  name: 'PYRAMID',  sub: '12×12 m base · 3×3 cells',     tag: 'HUB',    status: 'P1', glyph: 'Y' }},
  {{ id: 'sphere',   name: 'SPHERE',   sub: '⌀8 m · 2×2 cells',             tag: 'CORE',   status: 'P1', glyph: 'S' }},
];

const ACTIONS = ['SURVEY', 'CLEAR', 'PLANT', 'HAUL', 'WATCH', 'BUILD'];

const TUBE_CONTENT = [
  'closed pond', 'glass path top', 'vines', 'glass + wood', 'algae bioreactor',
  'herbs', 'berries', 'veggies', 'flowers', 'bees', 'birds', 'rabbits',
  'chicks', 'rainbow python', 'flying fox',
];

const PYRAMID_FN = [
  'reception', 'shop', 'grill', 'cafe', 'organics', 'tools', 'tech',
  'accums', 'chargers', 'delivery', 'post', 'play zone', 'outfit',
  'fabrics', 'leather', 'jewels', 'robots', 'sweets',
];

const PRYSM_MAT = ['wood', 'glass', 'metal'];

// map viewport: {W} × {H} units = {FRAME[0] / PX_PER_M:.1f} × {FRAME[1] / PX_PER_M:.1f} m
const MAP_W = {W}, MAP_H = {H}, CELL = {SCALE * 4:.0f}; // cell = 4 m
const METER = {SCALE}; // svg units per meter
const PLOT_AREA_M2 = {area_m2:.0f}; // 0.096 ha per google maps

const FLATS = [
  {{
    id: 'site-0', name: 'SITE 0', color: '#52e05a',
    fill: 'rgba(46, 160, 67, 0.30)',
    note: 'construction site · 0.096 ha · google maps',
    pts: {js(site)},
  }},
];

// neighbour parcel across the road (from the same screenshot)
const CONTEXT = {js([{'name': 'neighbour parcel', 'kind': 'certificates', 'pts': u(NEIGHBOUR_PX)}])};

// road + trails traced from the screenshot
const LINES = {js([{'name': 'road', 'pts': u(ROAD_PX)}] + [{'name': 'trail', 'pts': u(t)} for t in TRAILS_PX])};

const PLACES = [];

const MY_MAPS_ID = '1txZioQKBBvOdmox1Had5aI-Zz4kUEJI';

function defaultConfig(id) {{
  switch (id) {{
    case 'cube':     return {{ mode: 'unit', pax: 1, purpose: '', walls: [] }};
    case 'tube':     return {{ size: 'S', len: 8, content: ['closed pond', 'glass path top'] }};
    case 'prysm':    return {{ h: 2, mat: ['wood', 'glass'], modular: true }};
    case 'pyramid':  return {{ fns: ['reception', 'shop', 'cafe'] }};
    case 'sphere':   return {{ water: true, orangery: true }};
    default:         return {{}};
  }}
}}
"""
open('js/data.js', 'w').write(data)
print(f"site: {len(site)} pts · {AREA_HA} ha · {PX_PER_M:.2f} px/m · "
      f"view {FRAME[0] / PX_PER_M:.1f}×{FRAME[1] / PX_PER_M:.1f} m · {W}×{H} units")
