# regenerate js/data.js from the construction-site screenshot trace
# source: master-plan my-maps screenshot (818×738 px frame, north up).
# the white-border polygon is traced dot-by-dot; my-maps midpoint handles
# lie exactly on the edge, so including them keeps the outline exact.
# scale: the asphalt road in frame is ~14 px wide; assumed 4 m wide
# => PX_PER_M = 3.5. update PX_PER_M when the real area/size is known.
import json

PX_PER_M = 3.5           # approx: road ≈ 14 px ≈ 4 m
SCALE = 5.0              # svg units per meter (matches app)
PX2U = SCALE / PX_PER_M  # px -> svg units
FRAME = (818, 738)       # px

SITE_PX = [
    (302, 114), (413, 127), (523, 137), (536, 187), (556, 226),
    (604, 254), (658, 299), (713, 353), (779, 404), (738, 470),
    (688, 536), (611, 656), (390, 500), (165, 340), (208, 291),
    (250, 242), (277, 177),
]

ROAD_PX = [(818, 368), (786, 404), (747, 462), (700, 528),
           (646, 610), (607, 668), (578, 720), (560, 738)]

NEIGHBOUR_PX = [(818, 436), (760, 452), (700, 528), (648, 606),
                (600, 738), (818, 738)]

TRAILS_PX = [
    [(96, 368), (140, 300), (190, 225), (240, 150), (300, 80), (360, 40)],
    [(300, 80), (430, 70), (560, 60), (700, 90)],
    [(560, 60), (660, 120), (760, 220), (800, 300)],
    [(96, 368), (180, 420), (300, 480), (420, 560), (520, 650), (560, 738)],
]

u = lambda pts: [[round(x * PX2U, 1), round(y * PX2U, 1)] for x, y in pts]

site = u(SITE_PX)
W, H = round(FRAME[0] * PX2U), round(FRAME[1] * PX2U)

m = [(x / PX_PER_M, y / PX_PER_M) for x, y in SITE_PX]
area_ha = abs(sum(m[i][0] * m[(i + 1) % len(m)][1] - m[(i + 1) % len(m)][0] * m[i][1]
                  for i in range(len(m)))) / 2 / 10000

js = lambda v: json.dumps(v, ensure_ascii=False)

data = f"""// cyberia master map — catalog + construction site traced from master-plan screenshot
// scale: approx, road width ≈ 4 m => {PX_PER_M} px/m; north up; cell = 4 m
// generated by tools/trace_site0.py — edit the trace or PX_PER_M, then regenerate

const CATALOG = [
  {{ id: 'cube',     name: 'CUBE-4',   sub: '4×4×4 multipurpose cell', tag: 'CELL',    status: 'P0', glyph: 'C' }},
  {{ id: 'tube',     name: 'TUBE',     sub: 'living connector S · M',  tag: 'LINK',    status: 'P0', glyph: 'T' }},
  {{ id: 'prysm',    name: 'PRYSM',    sub: 'half-rhomb triangle',     tag: 'MODULE',  status: 'P1', glyph: 'P' }},
  {{ id: 'pyramid',  name: 'PYRAMID',  sub: 'reception · market · grill', tag: 'HUB',  status: 'P1', glyph: 'Y' }},
  {{ id: 'sphere',   name: 'SPHERE',   sub: 'water store + orangery',  tag: 'CORE',    status: 'P1', glyph: 'S' }},
];

const ACTIONS = ['SURVEY', 'CLEAR', 'PLANT', 'HAUL', 'WATCH', 'BUILD'];

const TUBE_CONTENT = [
  'closed pond', 'glass path top', 'vines', 'glass + wood', 'algae bioreactor',
  'herbs', 'berries', 'veggies', 'flowers', 'bees', 'birds', 'rabbits',
  'chicks', 'rainbow python', 'flying fox',
];

const PYRAMID_FN = [
  'reception', 'shop', 'grill', 'cafe', 'organics', 'tools', 'tech',
  'accums', 'chargers', 'delivery', 'post', 'play zone', 'outfit',
  'fabrics', 'leather', 'jewels', 'robots', 'sweets',
];

const PRYSM_MAT = ['wood', 'glass', 'metal'];

// map viewport: {W} × {H} units = {FRAME[0] / PX_PER_M:.0f} × {FRAME[1] / PX_PER_M:.0f} m (scale approx)
const MAP_W = {W}, MAP_H = {H}, CELL = {SCALE * 4:.0f}; // cell = 4 m
const METER = {SCALE}; // svg units per meter

const FLATS = [
  {{
    id: 'site-0', name: 'SITE 0', color: '#52e05a',
    fill: 'rgba(46, 160, 67, 0.30)',
    note: 'construction site · {len(site)} points · ≈{area_ha:.1f} ha (scale approx)',
    pts: {js(site)},
  }},
];

// neighbour parcel across the road (from the same screenshot)
const CONTEXT = {js([{'name': 'neighbour parcel', 'kind': 'certificates', 'pts': u(NEIGHBOUR_PX)}])};

// road + trails traced from the screenshot
const LINES = {js([{'name': 'road', 'pts': u(ROAD_PX)}] + [{'name': 'trail', 'pts': u(t)} for t in TRAILS_PX])};

const PLACES = [];

const MY_MAPS_ID = '1txZioQKBBvOdmox1Had5aI-Zz4kUEJI';

function defaultConfig(id) {{
  switch (id) {{
    case 'cube':     return {{ mode: 'unit', pax: 1, purpose: '', walls: [] }};
    case 'tube':     return {{ size: 'S', len: 8, content: ['closed pond', 'glass path top'] }};
    case 'prysm':    return {{ h: 2, mat: ['wood', 'glass'], modular: true }};
    case 'pyramid':  return {{ fns: ['reception', 'shop', 'cafe'] }};
    case 'sphere':   return {{ water: true, orangery: true }};
    default:         return {{}};
  }}
}}
"""
open('js/data.js', 'w').write(data)
print(f"site: {len(site)} pts · ≈{area_ha:.2f} ha (at {PX_PER_M} px/m) · "
      f"view {FRAME[0] / PX_PER_M:.0f}×{FRAME[1] / PX_PER_M:.0f} m · {W}×{H} units")
